import fs from 'node:fs/promises';

const IN = '/Users/techsaswata/Downloads/Wanderlust/capture/icons';
const OUT = '/Users/techsaswata/Downloads/Wanderlust/src/components/ui/icons.tsx';

// Hand-identified mapping from the deduped extraction to semantic names.
const MAP = {
  'icon-000': 'Heart',
  'icon-001': 'Star',
  'icon-002': 'ChevronRight',
  'icon-003': 'ChevronLeft',
  'icon-004': 'ChevronDown',
  'icon-005': 'ArrowRight',
  'icon-006': 'Globe',
  'icon-007': 'Facebook',
  'icon-008': 'XSocial',
  'icon-010': 'Search',
  'icon-011': 'AirbnbWordmark',
  'icon-012': 'AirbnbBelo',
  'icon-013': 'Menu',
  'icon-014': 'Instagram',
  'icon-015': 'Close',
  'icon-019': 'Plus',
  'icon-020': 'Minus',
  'icon-021': 'MapPin',
  'icon-022': 'Share',
  'icon-026': 'LocationPin',
  'icon-029': 'Settings',
};

/** Strip the <svg> wrapper, keep only the inner drawing markup. */
function inner(svg) {
  const m = svg.match(/<svg\b[^>]*>([\s\S]*)<\/svg>/);
  return (m ? m[1] : svg).trim();
}
function attrOf(svg, name) {
  return svg.match(new RegExp(`${name}="([^"]*)"`))?.[1] ?? null;
}
/** JSX-ify raw SVG child markup: kebab attrs -> camelCase, self-close voids. */
function toJsx(markup) {
  return markup
    .replace(/<(path|circle|rect|line|polyline|polygon|ellipse|stop)\b([^>]*?)\s*\/?>(?:<\/\1>)?/g,
      (_, tag, attrs) => `<${tag}${attrs} />`)
    .replace(/\s([a-z]+)-([a-z])/g, (_, a, b) => ` ${a}${b.toUpperCase()}`)
    .replace(/\sclass=/g, ' className=');
}

const entries = [];
for (const [file, name] of Object.entries(MAP)) {
  let raw;
  try { raw = await fs.readFile(`${IN}/${file}.svg`, 'utf8'); }
  catch { console.warn('missing', file); continue; }
  const viewBox = attrOf(raw, 'viewBox') || '0 0 32 32';
  const body = toJsx(inner(raw));
  // Airbnb's line icons use fill="none" + a stroke supplied by CSS.
  const isStroke = /fill="none"/.test(raw);
  entries.push({ name, viewBox, body, isStroke });
}

const header = `/**
 * Airbnb's production icon set, extracted from the live site and converted to
 * components. Path data is verbatim so shapes match pixel-for-pixel.
 *
 * GENERATED by tools/gen-icons.mjs — do not edit by hand.
 */
import type { SVGProps } from "react";

export interface IconProps extends SVGProps<SVGSVGElement> {
  /** Rendered width and height in px. */
  size?: number;
}

/** Line icons: stroke follows currentColor, width scales with the icon. */
const strokeProps = {
  fill: "none" as const,
  stroke: "currentColor" as const,
  strokeWidth: 2,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
};
`;

const comps = entries.map(({ name, viewBox, body, isStroke }) => {
  const extra = isStroke ? '      {...strokeProps}\n' : '      fill="currentColor"\n';
  return `
export function ${name}Icon({ size = 16, ...props }: IconProps) {
  return (
    <svg
      viewBox="${viewBox}"
      width={size}
      height={size}
      aria-hidden="true"
      role="presentation"
      focusable="false"
${extra}      {...props}
    >
      ${body}
    </svg>
  );
}`;
}).join('\n');

await fs.writeFile(OUT, header + comps + '\n');
console.log(`wrote ${entries.length} icons -> ${OUT}`);
entries.forEach(e => console.log(`  ${e.name}Icon  vb=${e.viewBox} stroke=${e.isStroke}`));
